### ISSUE TITLE
Feature request: columns resize handler

### ISSUE THREAD

**Issue by mekery** [GoCapsule/tiptap-extensions#3]
Great work!

Is there any plans to add handlers between columns to resize?

**Comment by leonard-henriquez** [comment]
Thank you @mekery !
I'm not sure what you mean by resize because the size of the column is only css style!
You can [customize with CSS only on your side](https://github.com/GoCapsule/tiptap-extensions#customization)

**Comment by mekery** [comment]
> Thank you @mekery ! I'm not sure what you mean by resize because the size of the column is only css style! You can [customize with CSS only on your side](https://github.com/GoCapsule/tiptap-extensions#customization)

Thanks for you reply.

I mean change the size dynamically by drag a handler between columns.
Let me show you an example: https://stackoverflow.com/a/46934825/5344687

Or you can try [Notion](https://www.notion.so/)'s column features.

**Comment by leonard-henriquez** [comment]
I would like to keep this extension the least opinionated as possible to allow use in different contexts. 

The drag handler is a bit too specific. For instance, it doesn't fit my use case (which is to build something like an editor with column [like this one](https://keystonejs.com/docs/guides/document-field-demo)).

But we could add a command like this:

```
editor.setColumnsWidth([x, y ,z])
```
x, y and z would be numbers that indicate the proportional size of each column.

What do you think?
Can you submit a PR to implement it?

**Comment by leonard-henriquez** [comment]
I'm closing the issue due to inactivity but don't hesitate to reopen if needed
