### ISSUE TITLE
CodeSandbox link on README.md not working

### ISSUE THREAD

**Issue by moxxuk** [GoCapsule/tiptap-extensions#4]
The link to the CodeSandbox demo is not working:

![image](https://user-images.githubusercontent.com/9335114/192249360-a93d9f10-daa1-4d76-b637-45ccbde1d7e6.png)

**Comment by leonard-henriquez** [comment]
I updated the links url which were updated.
Can you confirm they are working?
If not can you give me the url so I can fix it?
Thank you

**Comment by leonard-henriquez** [comment]
Seems resolved !
