### ISSUE TITLE
language agnostic implementation

### ISSUE THREAD

**Issue by marclave** [GoCapsule/tiptap-extensions#9]
Hey!

Love this package, I wasn't too familiar with React so I made an implementation of it in pure typescript so react or vue can use it!

https://github.com/marclave/extension-columns

Should I make a pr that follows this repo?

**Comment by leonard-henriquez** [comment]
Hi @marclave !
If you open a PR I would be happy to review and merge it !
Sounds like a good idea to make this project language agnostic

**Comment by marclave** [comment]
@leonard-henriquez cool, i'll do that later today! 😸

**Comment by marclave** [comment]
@leonard-henriquez sorry seemed like a weekend task!

I have the pull request ready but I couldn't push to the repo or make new branches.

Should I fork it?

**Comment by leonard-henriquez** [comment]
Thank you Marc !
You can fork it and make a PR from your repo to this repo 🙂 
I'll be happy to review it !

**Comment by marclave** [comment]
https://github.com/GoCapsule/tiptap-extensions/pull/10

done!

**Comment by marclave** [comment]
Closed in #10

**Comment by leonard-henriquez** [comment]
It has been released in v1.0.0-beta-3
